# Assumes that:
# 1. the following env variables are set:
# - ZIP_FILE_PATH
# - EXTENSION_DIR
# 2. repository checked out
# Effects:
# - builds and tests an extension, fails on error
# - packed extension.zip saved to env.ZIP_FILE_PATH if inputs.doNotPackZip == 'false'

name: "Build, test and pack WebExtension"
description: "Builds, tests, and packs extension dir into zip file"

inputs:
  doNotPackZip:
    description: 'Set `true` to omit pack step'
    required: false

runs:
  using: "composite"
  steps:
    # Add additional build and test steps here

    - name: Copy extension to folder
      shell: bash
      run: |
        mkdir -p ${{ env.EXTENSION_DIR }}
        cp manifest.json ${{ env.EXTENSION_DIR }}
        cp blocked.html ${{ env.EXTENSION_DIR }}
        cp -r config/ ${{ env.EXTENSION_DIR }}
        cp -r images/ ${{ env.EXTENSION_DIR }}
        cp -r options/ ${{ env.EXTENSION_DIR }}
        cp -r popup/ ${{ env.EXTENSION_DIR }}
        cp -r rules/ ${{ env.EXTENSION_DIR }}
        cp -r scripts/ ${{ env.EXTENSION_DIR }}
        cp -r styles/ ${{ env.EXTENSION_DIR }}

    - name: Pack directory to zip
      if: inputs.doNotPackZip != 'true'
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@28fdcac9860fb08555580587cab0d33afe4a341d
      with:
        extensionDir: ${{ env.EXTENSION_DIR }}
        zipFilePath: ${{ env.ZIP_FILE_PATH }}