name: Build and test
on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'dev'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cardinalby/export-env-action@66657b34899a2d695434ed060d9f2215db9b4035
        with:
          envFile: './.github/workflows/constants.env'
          expand: true

      - name: Build, test and pack to zip
        id: build
        uses: ./.github/workflows/actions/build-test-pack
        with:
          # pack zip only for pull requests or workflow_dispatch events
          doNotPackZip: ${{ github.event_name == 'push' && 'true' || 'false'}}

      - name: Upload zip file artifact
        if: github.event_name != 'push'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: ${{ env.ZIP_FILE_NAME }}
          path: ${{ env.ZIP_FILE_PATH }}